

package rmi.clientUI;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import rmi.server.register.ServerInterface;


public class ClientUI extends javax.swing.JFrame {
    
    private ServerInterface server;

    private boolean isStart; 
    private boolean access;
    private String username;
    
    public ClientUI() {
        initializeRMI();
        setTitle("RMI app");
        initComponents();
        
        this.setResizable(false);
        setEditableForCardNumberAndEncryptionTextField(false);
        
        setVisibleForEncryptionAndDecryption(false);
        
    }
    
        private void initializeRMI() {

        if ( isStart == false ) {
            try{
                final Registry reg = LocateRegistry.getRegistry(1099);
                server =(ServerInterface) reg.lookup("MyRMI");
                System.out.println("Server object " + server + " found");

            } catch (Exception e ) {
                e.printStackTrace();
            }
        }
    }
    
    private void setEditableForCardNumberAndEncryptionTextField(boolean b) {
        eEncryptionJTextField.setEditable(false);
        dCardNumberJTextField.setEditable(false);
        
    }
    
    private void setVisibleForEncryptionAndDecryption( boolean b ) {
        eCardNumberJLabel.setVisible(b);
        eCardNumberJTextField.setVisible(b);
        eEncryptedNumberJLabel.setVisible(b);
        eEncryptionJTextField.setVisible(b);
        eEncryptionjButton.setVisible(b);
        
        dCardNumberJLabel.setVisible(b);
        dCardNumberJTextField.setVisible(b);
        dCryptogramJLabel.setVisible(b);
        dCryptogramJTextField.setVisible(b);
        dDecryptionJButton.setVisible(b);
        
    }
    
    public void setIsStart(boolean is){
        isStart = is;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        usernameJLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passJLabel = new javax.swing.JLabel();
        passTextField = new javax.swing.JTextField();
        logInJButton = new javax.swing.JButton();
        eCardNumberJLabel = new javax.swing.JLabel();
        eCardNumberJTextField = new javax.swing.JTextField();
        eEncryptedNumberJLabel = new javax.swing.JLabel();
        eEncryptionJTextField = new javax.swing.JTextField();
        dCryptogramJLabel = new javax.swing.JLabel();
        dCardNumberJLabel = new javax.swing.JLabel();
        dCryptogramJTextField = new javax.swing.JTextField();
        dCardNumberJTextField = new javax.swing.JTextField();
        dDecryptionJButton = new javax.swing.JButton();
        eEncryptionjButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameJLabel.setText("Username:");
        usernameJLabel.setToolTipText("");

        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });

        passJLabel.setText("Password: ");

        logInJButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        logInJButton.setText("LogIn");
        logInJButton.setToolTipText("");
        logInJButton.setActionCommand("Log In");
        logInJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInJButtonActionPerformed(evt);
            }
        });

        eCardNumberJLabel.setText("card number :");

        eEncryptedNumberJLabel.setText("encrypted number:");

        dCryptogramJLabel.setText("cryptogram :");

        dCardNumberJLabel.setText("card number :");

        dDecryptionJButton.setText("decryption");
        dDecryptionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dDecryptionJButtonActionPerformed(evt);
            }
        });

        eEncryptionjButton.setText("encryption");
        eEncryptionjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eEncryptionjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eEncryptedNumberJLabel)
                            .addComponent(eCardNumberJLabel)
                            .addComponent(dCryptogramJLabel)
                            .addComponent(dCardNumberJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eCardNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eEncryptionJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(dCryptogramJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dCardNumberJTextField)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(usernameJLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(usernameTextField))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(passJLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(passTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logInJButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(eEncryptionjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addComponent(dDecryptionJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(logInJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passJLabel)
                            .addComponent(passTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCardNumberJLabel)
                    .addComponent(eCardNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eEncryptionjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eEncryptedNumberJLabel)
                    .addComponent(eEncryptionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dCryptogramJLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dCryptogramJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dDecryptionJButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dCardNumberJLabel)
                    .addComponent(dCardNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        usernameJLabel.getAccessibleContext().setAccessibleName("nameJLabel");
        usernameTextField.getAccessibleContext().setAccessibleName("usernameTextField");
        passJLabel.getAccessibleContext().setAccessibleName("passJLable");
        passTextField.getAccessibleContext().setAccessibleName("passTextField");
        logInJButton.getAccessibleContext().setAccessibleName("logInJButton");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInJButtonActionPerformed
        String username = usernameTextField.getText();
        String password = passTextField.getText();
        
        try {
            if(checkUsername(username) && checkPassword(password) 
                    && server.existUser(username, password) ){
                
                access = true;
                this.username = username;
                setVisibleForEncryptionAndDecryption(true);

                setStarsToPasswordTextField();
                
                usernameTextField.setEditable(false);
                passTextField.setEditable(false);
                
                logInJButton.setVisible(false);

            }
            else {
                System.exit(1);
            }
        } 
        catch (Exception e ) {
            e.printStackTrace(); 
        }
        
    }//GEN-LAST:event_logInJButtonActionPerformed

    private void setStarsToPasswordTextField(){
        if(passTextField.getText() != null ) {
            int lengthPassword = passTextField.getText().length();
            String textForPass = "";
            
            for(int i = 0 ; i < lengthPassword ; i++ ) { 
                textForPass += "*";
            }

            passTextField.setText(textForPass);
        }
    }
    private boolean checkUsername(String username){
        if(username != null && username != "") {
            if ( username.matches("[a-zA-Z]+\\d*.?|[a-zA-Z]+\\d*\\s[a-zA-Z]+\\d*")) {
                return true;
            }
        }
        return false;
    }
    private boolean checkPassword(String pass) {
        if(pass != null && !pass.equals("")) {
            if( pass.matches("\\d{3,}")) {
                return true;
            }
         }
        return false;
     }
    
    private void dDecryptionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dDecryptionJButtonActionPerformed
        if(access && dCryptogramJTextField.getText().matches("\\d{17}")) {
            try {
                if( server.userCanDecryption(username)) {
                    dCardNumberJTextField.setText(server.
                            decryptionCode(dCryptogramJTextField.getText()));
                }
                else {
                    dCardNumberJTextField.setText("Error: User don't have access");
                }
            }
            catch (Exception e) {
                e.printStackTrace();
            }
        }
        else {
            dCryptogramJTextField.setText(" incorrect input");
        }
        
    }//GEN-LAST:event_dDecryptionJButtonActionPerformed
    
    private void eEncryptionjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eEncryptionjButtonActionPerformed
        if(access && eCardNumberJTextField.getText().matches("\\d{17}") ) {
            try{
                if(server.userCanEncryption(username)) {
                    eEncryptionJTextField.setText(server.
                            encryptionCode(eCardNumberJTextField.getText()));
                }
                else {
                    eEncryptionJTextField.setText("Error: User don't have access");
                }
            }
            catch ( Exception e ) {
                e.printStackTrace();
            }   
        } else {
            eCardNumberJTextField.setText(" incorrect input");
        }
        
    }//GEN-LAST:event_eEncryptionjButtonActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ClientUI cc = new ClientUI();
                cc.setIsStart(true);
                cc.setDefaultCloseOperation(3);
                cc.setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dCardNumberJLabel;
    private javax.swing.JTextField dCardNumberJTextField;
    private javax.swing.JLabel dCryptogramJLabel;
    private javax.swing.JTextField dCryptogramJTextField;
    private javax.swing.JButton dDecryptionJButton;
    private javax.swing.JLabel eCardNumberJLabel;
    private javax.swing.JTextField eCardNumberJTextField;
    private javax.swing.JLabel eEncryptedNumberJLabel;
    private javax.swing.JTextField eEncryptionJTextField;
    private javax.swing.JButton eEncryptionjButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton logInJButton;
    private javax.swing.JLabel passJLabel;
    private javax.swing.JTextField passTextField;
    private javax.swing.JLabel usernameJLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
